### ISSUE TITLE
Skip CI for conflict PRs

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/backportbot#361]
Add `[ci skip]` to backport commits if we detect conflicts.

https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs
https://www.google.com/search?hl=en&q=drone%20ci%20skip%20ci

**Comment by ChristophWurst** [comment]
I would first restructure the code so we know if the conflict is dangerous or potentially ok. Clean cherry picks done need to be amended. Then the [skipci] in the commit message is cumbersome to get rid of.

PR at https://github.com/nextcloud/backportbot/pull/362

**Comment by nickvergessen** [comment]
At least on Github Actions it seems to only be "HEAD" so the last commit would be enough.
So in a case that compiling is needed `/compile /` (without amend) would be enough.

Same seems to apply on drone.
So that would be 90% coverage already with a change how to use the compile command.

And the PHP conflicts you need to resolve manually, we need to change the message on the last commit, sounds good enough?

**Comment by ChristophWurst** [comment]
The problem is that we first do all git operations, including the push. Later we create the PR and determine if it is conflicting based on the lines changed. To amend the last commit with skipci I need to move the conflict logic somehow.
